### PR TITLE
Beta features: Reviews, Review Assignments, and Reactions

### PR DESCRIPTION
**Pull request by ptsochantaris**
This PR is a work-in-progress and a place to post beta builds of Trailer 1.5.6 that supports beta Github API features, such as Reviews, Review Assignments, and possibly Reactions in the near future.

If you would like to try out these features and provide feedback or (more probably at this point) bug reports, please feel free to try out the latest build posted here. When there is a new build I will post a comment. Builds will be updated semi-regularly as bugs get fixed and feature support is rounded-out.

**Precautions:** These builds' stability right now can be described as "it works on my machine", although overall the chance that they would cause any harm to your system or existing Trailer setup are small, _but_ there may always be weirdness and/or breakage down the line. This means that if you want to try them out, you should back up your current Trailer DB so that you are able to downgrade to a previous version in the future, if need be. To do this, just keep a ZIPed version of `~Library/Application Support/com.housetrip.Trailer` somewhere, and if you want to downgrade just restore it to that location after downgrading Trailer.app from `Applications`. Also, make sure you export a copy of your settings from Preferences -> Misc and keep them in a safe place next to the DB. If you downgrade and your DB gets wiped, you can restore your settings and the Library files and you'll be right back where you started.

**Notes on first run:** because this version changes the way sync is done, initial syncs (or full item refreshes when some pivotal option has changed) will take longer but incremental syncs (i.e. the regular everyday ones) should be much faster and also more accurate. So, expect the first sync after you run this version, or after enabling the reviews feature, to take a little while longer than it used to. The reason for this is that the APIs are becoming constantly more and more spread out and "normalised", so trying to sync things quickly can end up triggering GitHub's abuse filters, so request concurrency in long-running syncs is reduced on the client-side. To compensate, this version uses a far smarter incremental sync mechanism, which means that while long syncs will take a bit longer, the syncs that are done every few minutes will be much faster and take even less bandwidth.

(last updated: 5 Apr 2017, 17:06)

### CODE REVIEW

**Comment by ptsochantaris** [comment]
New beta build

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/835950/Trailer.zip)

**Comment by aequitas** [comment]
Thanks for jumping on feature so early. 

I tested it again our Github Enterprise (2.8.7). No review status is displayed for items and the status icon shows a red 'x'. To me no discernible output is found in logging (search for 'trailer' in Console.app).

I believe our Github is lagging a few versions behind on public. So my expectation where: the feature does not work, normal operation still works. Btw, I tried with enabled and disabled options for Reviews.

**Comment by ptsochantaris** [comment]
Hi @aequitas and, first off, thanks for testing out the build and the feedback, it's really useful to know what's happening on the GE side of things, as I don't have access to one to verify how things work (or don't, like i this case :))

I'm thinking that your GE server currently doesn't support the review API, since it's a preview API. I'm guessing GitHub will include it in future releases of the GE server when they eventually mark the API as "non-beta" - or perhaps it may need to be enabled on the server via some flag or confutation option?

The red 'x' you see indicates that the last sync has failed. This almost certainly means an HTTP error code being received from an endpoint. This makes me think that Trailer is still trying to get some review-related data from the server, but maybe not. Make sure that the `When a PR is assigned to me for review...` option is also set to `None` in your preferences while trying to sync.

If this doesn't fix things, to get a better idea of where the sync is failing, check out the log that is being written by the build - at some point the client will be receiving an HTTP error code, like a 40[1,3,4] or perhaps even a 500? If you can spot which URL it is that's breaking (or rather, which endpoint) I can try to investigate and see why that's being called and where the breakage is occurring.

**Comment by aequitas** [comment]
Glad to be of help. Our version surely does not contain the review API thats why I wasn't expecting much :). I'll keep a watch on this thread to update you on any future beta releases.

I didn't consider changing that dropdown. I set it to `Don't move it` and synchronization now completes with no errors. 

The problem API call was a 404: 
```13/03/17 12:03:27,315 Trailer[62200]: (Avira) GET https://github.dtc.avira.com/api/v3/repos/AMSS/ames.deliveryengine/pulls/79/requested_reviewers - FAILED: (code 404) Server responded with error 404
```

**Comment by ptsochantaris** [comment]
> I didn't consider changing that dropdown. I set it to Don't move it and synchronization now completes with no errors.

That's good to know, and thanks for getting back with this feedback. It suggests that the UI in the "reviews" box needs a bit of work from my end, which isn't a shocking revelation at this time :) but good to have it confirmed.

The long version :) - The issue there is that there are two separate kinds of API endpoint accessed by these options, even though they are all related to reviews. One is the reviews themselves and their comments, and the other is what GH calls "review_assignments". They are both missing from your server. When that dropdown wasn't set to "none" Trailer was still polling the assignments APIs to try and see what was assigned and if so, should it move it somewhere else, etc. When you set it back to none, there was no longer any need to 👍

**Comment by ptsochantaris** [comment]
New beta build - halved API calls related to reviews (with many thanks to GitHub support for some invaluable tips)

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/839033/Trailer.zip)

**Comment by ptsochantaris** [comment]
Updated build - improved (relevant) review filtering, and also displaying approvers rather than just blockers. Builds are now signed and built with optimisations.

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/843856/Trailer.zip)

(As before, please ignore the "reactions" section in the preferences, it currently does absolutely nothing)

**Comment by ptsochantaris** [comment]
Updated build with review options off by default (this was an oversight, reviews should be off by default for API usage and beta API usage reasons - if you're already using a beta with reviews, you may want to go into preferences and turn the various review options back on)

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/844318/Trailer.zip)

(As always, please ignore the "reactions" section in the preferences, it currently does absolutely nothing)

**Comment by kevinjalbert** [comment]
@ptsochantaris this is looking great!

I did notice that if someone had requested changes _N_ times their name would also appear _N_ times in Trailer. GitHub seems to only look at the latest review event in the sidebar for reviews as well as in the PR checks.

Is this something that Trailer should do as well? In my personal usage I really only care about the last request as things has likely changed since the previous one.

**Comment by ptsochantaris** [comment]
@kevinjalbert I totally agree. It seems that, while the GH API actually provides a list of reviews which can include multiple reviews per user, it seems to coalesce them per-reviewer when it come to the "merge box", and it picks the latest approved/not-approved state from that. I'll update the beta to do the same 👍

**Comment by ptsochantaris** [comment]
Updated build - Improved review display, includes reviewers who are assigned but haven't reviewed yet.

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/848656/Trailer.zip)

This build has preliminary and *very buggy* support for reactions. Added to this there are some bad caveats, so please read on if you want to try this out (better yet, don't :))

- It's buggy, expect that you will miss reactions, and that you may even have failed syncs, etc.
- The reaction options are partly enforced, right now you will get notifications for every reaction, anywhere.
- The GitHub API seems to not be able to serve both reactions and reviews at the same time - it seems that only one preview API can be used at a time (which is a bit weird, so I'll double-check it with them)  This means that if you enable reactions, you MUST disable all options (and dropdown) in "Reviews", and vice-versa: If you enable reviews, all options in "Reactions" must be disabled.
- In general, hold off for a few builds :)

**Comment by ptsochantaris** [comment]
Updated build - Smaller tweaks this time around: Fixed a bug when being alerted about high API usage, added a blocker in preferences to disallow both Reviews and Reactions support to be enabled simultaneously (and hence breaking sync), and applying the actual options in the Reactions panel to reactions.

Reaction sync is still broken - either full polling needs to be done or some other "smart" way found to locate reactions, since timelines don't seem to show reaction events.

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/853094/Trailer.zip)

**Comment by ptsochantaris** [comment]
Updated build - Bugfixes related to items being marked as dirty from the event stream, slightly faster initial event check "burst", more items per-page hopefully resulting in slightly fewer calls in cases of lots of items (or reviews, comments, reactions, etc), and sturdier reactions settings handling.

Reaction sync is still broken (or, to clarify: notifications for reactions may never arrive or be very slow to arrive) - either full polling needs to be done or some other "smart" way found to locate reactions, since timelines don't seem to show reaction events. Going to contact GitHub to see if there are any alternatives to just re-scanning everything, like we have to do with statuses :(

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/855826/Trailer.zip)

**Comment by ptsochantaris** [comment]
Updated build - improvements in cases where a click on a menu item is mis-identified as a drag.

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/859275/Trailer.zip)

**Comment by ptsochantaris** [comment]
Updated build - fix for displaying expected reviewers, even if no approvals or change expectations have been created.

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/862499/Trailer.zip)

**Comment by ptsochantaris** [comment]
Some feedback from GitHub on being able to access two preview features simultaneously: Unfortunately it isn't possible. It may be in the future at some point, but it's safe to assume not in the timeline of this beta.

On syncing reactions properly: Unfortunately there is no way to tell when reaction is created using the REST API at this time, so Trailer will have to deal with reactions the same sub-optimal way it deals with statuses, i.e. re-scanning all related items every X refreshes :( It's not horrible but, like with statuses, it slows down sync a bit if you have many items listed. I will be implementing this soon for a beta build.

**Comment by ptsochantaris** [comment]
Updated build - This version should be the first one that actually syncs reactions correctly. Right now the sync may be a bit wasteful on API, but (in theory) reactions should come down as they are added in a relatively reasonable amount of time. If you plan to use the reactions feature expect bumps, this will keep getting polished in the near future.

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/869240/Trailer.zip)

**Comment by ptsochantaris** [comment]
Updated build with the changes above. Overall improved review notifications, slightly better reaction sync, comment counts respond to reviews and reactions, and some UI fixes.

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/870185/Trailer.zip)

**Comment by ptsochantaris** [comment]
Suggestion from a colleague: Use a red/green icon to the notifications about "changes requested" and "changes approved" rather than the requester/approver's user avatar. Makes sense to me. Noting it down here in case there are any objections (and also so I don't forget, if there are none :))

**Comment by ptsochantaris** [comment]
Updated build - Built on Xcode 8.3 and Swift 3.1, hopefully faster and more stable 🤞

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/873436/Trailer.zip)

**Comment by ptsochantaris** [comment]
Suggestion from self: Approvals/rejections/etc. made by the current user should not send out notifications.

**Comment by ptsochantaris** [comment]
Updated build with fix for reviews.

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/900031/Trailer.zip)

**Comment by ptsochantaris** [comment]
Updated build with the above updates.

[Trailer.zip](https://github.com/ptsochantaris/trailer/files/900649/Trailer.zip)

**Comment by ptsochantaris** [comment]
At this point this build should be considered an RC, I think.

Thank you for trying out this beta and the suggestions!

Please feel free to post any last-minute bugs or issues you feel are relevant to reviews or reactions support and haven't been addressed by this time.

If there are none, I will be putting this update up on the auto-update feed by the end or the beginning of next week.

**Pull request merged**
