### PR TITLE
v1.8.0 Beta

### PR DESCRIPTION
**Pull request by ptsochantaris**
#### What's new in v1.8.0:
- Significant optimisations to performance throughout, from HTTP requests, parsing queries, processing items, app responsiveness while syncing, and especially updating menus in macOS.
- A (first) round of improvements to the ageing codebase :)
- Many small fixes, partly as a consequence of the cleanup
- Corrections to Spotlight integration

Current beta builds (please leave feedback in this PR thread with any issues you encounter)

#### Beta 2 - 20 Feb 2023
[TrailerBeta2.zip](https://github.com/ptsochantaris/trailer/files/10786086/TrailerBeta2.zip)

#### Beta 3 - 25 Feb 2023
[TrailerBeta3.zip](https://github.com/ptsochantaris/trailer/files/10829948/TrailerBeta3.zip)

#### Beta 4 - 5 Mar 2023
[TrailerBeta4.zip](https://github.com/ptsochantaris/trailer/files/10890569/TrailerBeta4.zip)

#### Beta 5 - 11 May 2023
[TrailerBeta5.zip](https://github.com/ptsochantaris/trailer/files/11449634/TrailerBeta5.zip)

#### Beta 6 - 4 Jun 2023
[TrailerBeta6.zip](https://github.com/ptsochantaris/trailer/files/11645361/TrailerBeta6.zip)

#### RC 2 - 17 Jun 2023
[TrailerRC2.zip](https://github.com/ptsochantaris/trailer/files/11780034/TrailerRC2.zip)

#### RC 3 - 25 Jun 2023
[TrailerRC3.zip](https://github.com/ptsochantaris/trailer/files/11860689/TrailerRC3.zip)

### CODE REVIEW

**Comment by XenoPhex** [comment]
Any chance we can get a new beta release? Thank you for all this recent work!

**Comment by ptsochantaris** [comment]
@XenoPhex Absolutely, just a soon as I am reasonably convinced the changes above haven't broken anything serious 😄

**Comment by ptsochantaris** [comment]
Added a new beta, which involves a lot of JSON handling updates so please do give a shout if you spot issues.

**Comment by ptsochantaris** [comment]
RC (1?) is now up - https://github.com/ptsochantaris/trailer/files/11779840/TrailerRC1.zip

Please shout if you spot any breaking issues!

**Comment by ptsochantaris** [comment]
And 5 minutes later RC2 because obviously :)

https://github.com/ptsochantaris/trailer/files/11780034/TrailerRC2.zip

**Comment by ptsochantaris** [comment]
Added (hopefully final) RC3
[TrailerRC3.zip](https://github.com/ptsochantaris/trailer/files/11860689/TrailerRC3.zip)

**Comment by ptsochantaris** [comment]
A huge thank you to anyone who has downloaded and tested this version. I'm going to merge this in now and update the public release shortly. Your beta copy should offer an update to the final app for you, so you don't need to do anything special to update to the release version. Many thanks again, and please do open issues for any problems you encounter in this version!

**Pull request merged**
