### PR TITLE
Watch the Trailer

### PR DESCRIPTION
**Pull request by ptsochantaris**
- Watch app with sections, statuses and comments
- Watch glance can be switched between PRs or Issues
- Today widget extension
- Appearance improvements
- CI/status notifications
- Team mention support
- Import & Export settings
- QuickStart for new users
- Swift 1.2 for better performance and stability
- Issues supported on all platforms
- Corrections for vibrancy issues

Suggestions and bug reports are very welcome on these features - if anyone would like to use the OS X specific features right now, please find test builds below.

trailer-13-extensions

trailer-13-issue-support

trailer-quickstart

### CODE REVIEW

**Comment by ptsochantaris** [comment]
v.1.3.0 Test build 1 for OS X - It "feels" stable, but as always please DO employ caution in where you will run it depending on how mission-critical the environment is.

** Please be sure to backup your Github token first, as downgrading to an earlier version will wipe your database, resetting your tokens and your repo-hiding settings **

https://www.dropbox.com/s/e7su2e3belnjy2r/Trailer-13-TEST1.zip?dl=0

**Comment by ptsochantaris** [comment]
Test build 2 - tweaks/fixes, plus compiled with Swift 1.2 / Xcode 6.3 for improved performance. Same warnings apply as above :)

https://www.dropbox.com/s/e8fa3t53m38p84z/Trailer-13-TEST2.zip?dl=0

**Comment by ptsochantaris** [comment]
Test build 4 - new quick start window and minor bug fixes:

https://www.dropbox.com/s/b8w5vkg9z4dw95n/Trailer-13-TEST4.zip?dl=0

**Comment by appleprtest** [comment]
test comment

**Comment by appleprtest** [comment]
test comment

**Comment by ptsochantaris** [comment]
v.1.3.0 Test build 5 for OS X - It's stable, but as always please DO employ caution in where you will run it depending on how mission-critical the environment is.

** Please be sure to backup your Github token first, as downgrading to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/96s9lghr8d08kzt/Trailer-13-TEST5.zip?dl=0

**Comment by ptsochantaris** [comment]
v.1.3.0 Test build 6 for OS X - It's stable, but as always please DO employ caution on where you will run it depending on how mission-critical the environment is.

** Please be sure to backup your Github token first, as downgrading back to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/7ivmftuvd86tm98/Trailer-13-TEST6.zip?dl=0

**Comment by ptsochantaris** [comment]
v.1.3.0 Test build 7 for OS X - It's stable, but as always please DO employ caution on where you will run it depending on how mission-critical the environment is.

** Please be sure to backup your Github token first, as downgrading back to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/srtzebx2ya07t4d/Trailer-13-TEST7.zip?dl=0

**Comment by mauricerkelly** [comment]
@ptsochantaris The menu in the main PRs interface is missing the “Mark All As Read” menu text. (Sorry if this is known)

screenshot of trailer 03-04-2015 21 03 06

**Comment by ptsochantaris** [comment]
@mauricerkelly Wow, no idea how that one happened, will patch it up, thanks! (PS I hadn't noticed it, so don't assume any bug that you notice is known :))

**Comment by ptsochantaris** [comment]
v.1.3.0 Test build 8 for OS X - It's stable, but as always please DO employ caution on where you will run it depending on how mission-critical the environment is.

** Please be sure to backup your Github token first, as downgrading back to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/0fhi9dv1aorri0p/Trailer-13-TEST8.zip?dl=0

**Comment by ptsochantaris** [comment]
v.1.3.0 Test build 9 for OS X - It's stable, but as always please DO employ caution on where you will run it depending on how mission-critical the environment is.

** Please be sure to backup your Github token first, as downgrading back to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/euexbc54nvlz445/Trailer-13-TEST9.zip?dl=0

**Comment by ptsochantaris** [comment]
v.1.3.0 Test build 10 for OS X - It's stable, but as always please DO employ caution on where you will run it depending on how mission-critical the environment is.

** Please be sure to backup your Github token first, as downgrading back to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/jxe2nfv8xauw4aw/Trailer-13-TEST10.zip?dl=0

**Comment by ptsochantaris** [comment]
v.1.3.0 Test build 11 for OS X - It's stable, but as always please DO employ caution on where you will run it depending on how mission-critical the environment is.

** Please be sure to backup your Github token first, as downgrading back to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/j96mk6ovcifd8ue/Trailer-13-TEST11.zip?dl=0

**Comment by ptsochantaris** [comment]
v.1.3.0 Release Candidate 1 for OS X

** Please be sure to backup your Github token first, as downgrading back to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/5uo6di2af0cob80/Trailer-13-TEST12.zip?dl=0

**Comment by ptsochantaris** [comment]
v.1.3.0 OS X Release Candidate 2

** Please be sure to backup your Github token first, as downgrading back to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/4zug3o4x7ipt91u/Trailer-13-RC2.zip?dl=0

**Comment by ptsochantaris** [comment]
v.1.3.0 OS X Release Candidate 3

** Please be sure to backup your Github token first, as downgrading back to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/thjwyblb0x29lg5/Trailer-13-RC3.zip?dl=0

**Comment by ptsochantaris** [comment]
v.1.3.0 OS X Release Candidate 4

Getting close to release now, if you DO spot anything please give me a shout, because I've very probably missed it :)

** Please be sure to backup your Github token first, as downgrading back to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/qxoix42fqwq95yo/Trailer-13-RC4.zip?dl=0

**Comment by ptsochantaris** [comment]
v.1.3.0 OS X Release Candidate 5

Unless a show-stopper is found, this will most probably be the released version (with just a build number bump)

** Please be sure to backup your Github token first, as downgrading back to 1.2.x will wipe your database, resetting your tokens and repo settings **

https://www.dropbox.com/s/4xve96i7r132afq/Trailer-13-RC5.zip?dl=0

**Comment by ptsochantaris** [comment]
Ok, I think the OS X build is good to go - fingers crossed as always, will be putting v1.3.0 up today :+1:

**Pull request merged**
