### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MithulGarg**
I was just looking through your repo because I use Trailer all the time, and was curious if I could contribute when I noticed there was some slight typo and I was trying to fix the license so that it would show up properly as a quick link in the repo details. Was using this link to help me fix it, but using the template and changing it to add the separate line for parts copyright threw it off and was not able to automatically detect the license file. I used this [Licensing tutorial link](https://help.github.com/articles/licensing-a-repository/) to learn more about licensing.

### CODE REVIEW

**Comment by ptsochantaris** [comment]
Hi @MithulGarg and thanks for the PR. Apologies for taking so long to reply, winter has been very busy work-wise.

I like how this makes the License links much tidier, that's great, but why remove the Copyright statements too? Could they perhaps be moved to a copyright section above the License section?

**Comment by MithulGarg** [comment]
Hi @ptsochantaris no worries, I just wanted to get my feet wet in open source and thought this was a good way to start! I think I saw on a few other repos that their license files were already including the copyright info, and so I figured it would make it cleaner to just have it in one place instead of in the readme and the license file.

**Comment by ptsochantaris** [comment]
In that case, I should say a very delayed welcome to the world of open source!

First off, I definitely appreciate your contribution. My question isn't so much about why are we moving things around, that's fine, but if you notice the PR itself doesn't move the copyright info (unless I'm mistaken), it just deletes it. That's my question really - could we keep the copyright info, perhaps in its own section? If so I'd be more than happy to merge this in and keep things tidy.

**Comment by MithulGarg** [comment]
Thank you! Yes I believe I just removed it because it was already in the license file, but that is not a big deal as we can keep it in the readme as well! I'll go ahead and update the PR

**Comment by ptsochantaris** [comment]
Great stuff. Thanks for helping keep this repo tidy. Will merge this now. Future contributions are always welcome!

**Pull request merged**
