### PR TITLE
Trailer 1.7.0 Beta

### PR DESCRIPTION
**Pull request by ptsochantaris**
Happy 2020!

This update adds some new features as well as the groundwork for introducing new ones via the new GitHub v4 API. Since it involves quite a few changes under the hood, a bit of beta testing would be greatly appreciated, links below!

### New features

- Added option to use GitHub v4 API for syncing data. If you sync a large amount of PRs, Repositories, sync status items, responses and/or review statuses/assignments, then turning this option on can result in dramatic speed improvements when syncing (and a reduction in corresponding API usage) since the number of calls Trailer has to make is significantly reduced. Trailer needs to migrate some data before being able to turn this option on, if you have existing data, so you will have to sync all servers at least once before being able to turn this option on.
- v3 API sync also features various improvements and optimisations to speed up some operations.
- Option to display teams that have been assigned to review a PR.
- Option to mark merge conflicts in PRs _(v4 API only)_
- Option to show added/removed line counts in PRs, as well as the ability to sort using that as a criterion _(v4 API only)_
- Option to scan closed and merged items for new events like comments and reactions _(v4 API only)_
- Options to scan items created on any repository, irrespective of whether they are in the watchlist _(v4 API only)_
- Reaction and status scanning logic has changed to keep syncs sane and help them scale up for larger numbers of items. From now on, Trailer will scan a fixed amount of items for statuses and reactions on every sync, and will round-robin through all items. So if you sync 200 items, and you’ve set 50 items per refresh, then all items will be refreshed within 4 syncs.
- PR branch names shown in context menus, selecting them copies the branch name to the clipboard.
- Various minor bug fixes and tweaks across both macOS and iOS.

### macOS
- Improvements to colours and dark mode handling.
- Improvements to keyboard handling in the repository list editor.
- Notarised binary for greater security.

### iOS
- iOS is now mature enough, and has enough handling for windowing and multitasking that it makes no sense to have an in-app web view and split-screen detail view on the iPad. Instead Trailer now works on iOS the same way it works on macOS - i.e. as a directory of items, and leaves opening and handling the URL of each item to the system. For instance, on iPad you can now set up your own split-screen by dragging an entry to the side of the screen and creating a new Safari window.
- Major UI refresh for iOS 13, including improved system appearance support, iOS native system icons, context menus for items, and many miscellaneous UI fixes.

### Installing the beta:
macOS: https://whisper.chat/trailer-beta/Trailer170-rc2.zip
iOS: https://testflight.apple.com/join/Q08QBYax

If you want to be totally safe and be able to rollback to an earlier release, remember to back up your data folder in `~/Library/Application\ Support/com.housetrip.Trailer`

### CODE REVIEW

**Comment by stembrain** [comment]
Cool, would love to help test this. I like this list of performance improvements. A+ release notes :)

**Comment by iserko** [comment]
Hi @ptsochantaris just tried this new beta version (fresh settings) and can't connect to my company's Github Enterprise instance (we're on the latest 2.19.6 version, so it definitely has the v4 API)

Basically looks like there's some path conversion going on for the graphql endpoint and messing it up.

The normal setting is `https://git.example.com/api/v3`
For graphql the endpoint is `https://git.example.com/api/graphql`, but looks like Trailer is going to `https://git.example.com/api/v3/graphql`

**Comment by ptsochantaris** [comment]
Hi @iserko and thanks for trying the v4 sync on a GE instance, I haven't had a chance to, so your feedback is extremely useful. It sounds from what you describe that I need to add separate v3 and v4 API paths in the preferences for each server, since GE instances seem to have a separate path, just like they do with their v3 API. I'll add this and get back to you very soon.

**Comment by ptsochantaris** [comment]
Hi @iserko - this ZIP is from a build where I've added a new field for servers where you can specify a manual API path, in the same way you specify the v3 API path. Could you give it a go when you have some time and let me know if it works correctly now with your GE server? Thanks!

[Trailer170-beta6-rc2.zip](https://github.com/ptsochantaris/trailer/files/4176752/Trailer170-beta6-rc2.zip)

**Comment by iserko** [comment]
@ptsochantaris amazing the new field you added fixed it.

Now I'm getting something else:
```
(GQL 'Github Enterprise: Open Issues')  Error: Failed with error: 'This query requests up to 703,535 possible nodes which exceeds the maximum limit of 500,000.'
```

Any ideas?

**Comment by ptsochantaris** [comment]
Ah, interesting. Yes, it's related to how many items the app is trying to fetch at once. Seems like it needs to be smarter about calculating the maximum number of items it can request to be checked concurrently. In this case it's trying to fetch too many records associated with issues. I need to take a closer look at that. Thanks for reporting these, this is very useful feedback! I'll get back to you very shortly with tweaks to hopefully improve this.

**Comment by ptsochantaris** [comment]
@iserko Can you give a try with this one? It may take a couple of iterations before we get it right, so bear with me if possible :)

[Trailer170-beta6-rc3.zip](https://github.com/ptsochantaris/trailer/files/4182274/Trailer170-beta6-rc3.zip)

**Comment by iserko** [comment]
@ptsochantaris no problem being the guinea pig :)

requested 502,550 nodes this time 😄 

```
default	19:50:05.573287+0000	Trailer	(GQL 'Github Enterprise: Open Issues') Received page (No stats)
default	19:50:05.573575+0000	Trailer	(GQL 'Github Enterprise: Open Issues')  Error: Failed with error: 'This query requests up to 502,550 possible nodes which exceeds the maximum limit of 500,000.'
```

**Comment by ptsochantaris** [comment]
Damn, so close :) However this tells me that Trailer is basically not following a sound querying pattern right now, although admittedly it's very easy to run afoul of the complex timeout/node count/complexity requirements of the v4 endpoint. Going to dig a bit into how I can improve this and come back with another build very shortly. Thanks so much once again for your help in this!

**Comment by ptsochantaris** [comment]
Have a go with this one @iserko - Just did some spreadsheet-ing and the theoretical max of each query should be below the 500k node limit now - the incremental refreshes should also work well I hope 🤞 

[Trailer170-beta6-rc4.zip](https://github.com/ptsochantaris/trailer/files/4183091/Trailer170-beta6-rc4.zip)

**Comment by iserko** [comment]
@ptsochantaris that version works fine 🎉

**Comment by ptsochantaris** [comment]
Awesome, thanks so much for testing it out, I'll update the "official" beta build now. Please _do_ let me know if you encounter more issues!

**Comment by maxwellainatchi** [comment]
@ptsochantaris is this thread where you want reports of regressions with the beta builds?

**Comment by ptsochantaris** [comment]
@maxwellainatchi Yes please, the more the better! 👍

**Comment by maxwellainatchi** [comment]
There's a bug in the latest beta (build 1543) where mousing over some PRs will cause the review status to change between "approved" and "requests changes" (including the color of the text and the text itself). If you need a video, let me know, I just need to censor some information from it

**Comment by ptsochantaris** [comment]
@maxwellainatchi That sounds like a very weird bug indeed - I don't think I'd need a whole video but perhaps a couple of screenshots demonstrating it? Does this occur on a public repo by any chance? Also, what OS version are you using?

**Comment by maxwellainatchi** [comment]
It's a private repo, macOS Catalina (10.15.3). The screenshots would just be PRs with different approval statuses. It has nothing to do with the current mouse position, it just potentially triggers a change when the mouse moves while above the PR entry. Also, it seems like it might only happen on PRs where the status was "requests changes" and is now "approved". I'm expecting a PR of mine to be approved soon, so I will update you once I know

**Comment by iserko** [comment]
@ptsochantaris might not be a bug or related to the beta, but I'm seeing some weird things.

Trailer is notifying me of PRs that I haven't participated in only when they are closed. I don't see them when they're opened though.

I have the repositories set to only show PRs that I participated on.

It's getting a bit annoying.

Any tips on how to debug this one?

**Comment by ptsochantaris** [comment]
@iserko Sounds like a regression caused from the recent work to sync and scan closed and merged PRs, taking a look and will update asap.

**Comment by ptsochantaris** [comment]
Hi @iserko - can you give this one a spin and see if it improves things for you? It also features some deep tweaks to syncing on the GraphQL API, but hopefully nothing too horrible will happen :)

[Trailer170-beta7-rc1.zip](https://github.com/ptsochantaris/trailer/files/4208373/Trailer170-beta7-rc1.zip)

**Comment by iserko** [comment]
@ptsochantaris looks like you fixed it. Haven't received a single notification for a PR I don't contribute to 🎉

**Comment by kamilpp** [comment]
Hi! What has to be done to enable "Use Github v4 API"? I did "Reload All Data" in the "Misc" tab so synced everything from scratch and there are no closed/merged PRs on my list (just 1 participated issue, several own PRs and several participated PRs). Still I am getting "Can't be turned on yet". Cheers!

**Comment by ptsochantaris** [comment]
Hi @kamilpp and sorry for the late reply. Trailer basically needs to migrate your existing DB from using the old number-style identifiers for items to the new UDID-style identifiers before it can proceed with turning on the v4 API support, as the v4 API uses strictly UDID identifiers.

The fact that you did a full reload of data and it's still giving you that makes me think that there may be a bug in the migration code there, or some hidden leftover items, and that an option to "clear all items and re-load with v4" may be a good idea when selecting the v4 switch.

That said, the fastest way you can un-block yourself right now would be to export your settings, delete com.housetrip.Trailer from your Library application support folder, launch Trailer fresh and turn on the v4 switch. I hope this helps - let me know how it goes, and I'll look into making the "reload everything" button a bit more... thorough in its data-wiping in the meantime to avoid anyone else in the future having the same issue.

**Comment by kamilpp** [comment]
Hi @ptsochantaris, thanks for your tips. I am afraid it didn't work either. 

Screen Shot 2020-03-09 at 16 24 23

Tried several times and it hangs on the welcome "fetching" screen, when API v4 is enabled.  I tried various combinations of dropping `com.housetrip.Trailer` and setting the app from scratch or from settings but it never worked with v4 enabled or I was not able to turn it on. 

Is there anything I can check for you to help in debugging? I have a log file I could share through pm.

**Comment by ptsochantaris** [comment]
Hi @kamilpp - thanks for the update, it's interesting in two ways, one is about the watchlist download and the other is about the refresh never completing.

Firstly, on the watchlist issue, what's interesting is that there is no difference in the code between v3 and v4 for fetching your initial watchlist, so using v4 should theoretically have no effect on that stage of the app. However, clearly _something_ was going on there, and I can't quite think of what. Perhaps some logging would help there.

On the second issue, what you are most likely seeing there are v4 API timeouts. The v4 API is really badly done on the server-side - while it actually has quotas and built-in maximum query requirements, certain queries can still randomly time-out when making the call. For this reason, Trailer on v4 API will automatically retry a call. However for some configurations it always times-out, and it seems to be pretty hard to tell how and why that happens yet. I have been making some querying tweaks to help reduce the incidence of these, and this is a more recent build to try out, which has been working well for me recently. Can you give it a shot and let me know how it goes?

BTW you can use Console.app (combined with the logging options in "Misc") to monitor the operations Trailer is making, if timeouts are happening, you can see it there. From this build going forward, you can also use the command-line log command: `log stream --type log --predicate 'process == "Trailer"'` for example will give you a dump of everything Trailer is doing API-wise (again, as long as the logging options are on in "Misc")

Sorry you're having headaches with this, but your help in testing this release is hugely appreciated. Let me know how it goes and if it still gives you issues we'll keep tweaking!

[Trailer-beta7-1.zip](https://github.com/ptsochantaris/trailer/files/4313802/Trailer-beta7-1.zip)

**Comment by kamilpp** [comment]
Hi @ptsochantaris,

I used the command you provided to save the logs while using v4 (log includes the range from opening the trailer app, waiting a while, clicking "refresh" and waiting till "refresh" button becomes available again). Hope it tells you something

[trailer2.log](https://github.com/ptsochantaris/trailer/files/4374668/trailer2.log)

**Comment by ptsochantaris** [comment]
Hi @kamilpp and thanks for testing it out and updating me 👍 

From your log it seems that what's happening is the timeout I described above. Clearly I haven't calibrated the payload sizes well for users with many repositories (I only have around 20 on my Trailer)

I'm including 3 variants of the above build, which alter the default repo batch size (currently 100) to 10 repos, 20, and 50 repos respectively. If you find some time to try out each one (I'd start with the smallest one (10)) to see if any or all correct your issue and let me know, it would very very helpful indeed. Note that the smaller the batch sizes the more time it may take a sync to complete, however you should not see any timeout errors in your logs if all goes well.

Let me know how it goes! Thanks again!

[Trailer-10.zip](https://github.com/ptsochantaris/trailer/files/4378207/Trailer-10.zip)

[Trailer-20.zip](https://github.com/ptsochantaris/trailer/files/4378208/Trailer-20.zip)

[Trailer-50.zip](https://github.com/ptsochantaris/trailer/files/4378210/Trailer-50.zip)

**Comment by kamilpp** [comment]
Thanks @ptsochantaris!

Both Tailer-10 and Trailer-20 work for me without issues. Trailer-50 fails to update most of the times. I am staying with Trailer-20 right now. 

One more remark. We did the test of the feature I was really looking forward:
image

Unfortunately, such comment is not poping up in trailer after refreshing:
image

**Comment by ptsochantaris** [comment]
Thanks for taking a look @kamilpp - sounds like the GitHub API is far more sensitive than it lets on :( My concern with a value like 20 is that this means Trailer needs to make a new v4 API call for every 20 repositories you have, making the point (and speed) of v4 sync a little less effective, but this can possibly be improved by a user-configurable setting in the future. For now, thanks for testing this, and I'm glad it's temporarily at least solving your issue.

I'm going to dig into the closed/merged PR issue now - I wonder if I inadvertently broke something while tweaking the API in the meantime. Will update you soon, and thanks again.

**Comment by ptsochantaris** [comment]
Hi @kamilpp this build should correct that regression in the closed/merged items issue (mea culpa!) Have a go and let me know if it improves things for you.

[Trailer-1555.zip](https://github.com/ptsochantaris/trailer/files/4417139/Trailer-1555.zip)

**Comment by ptsochantaris** [comment]
Above build updated with some fixes:

[Trailer-1556.zip](https://github.com/ptsochantaris/trailer/files/4417640/Trailer-1556.zip)

**Comment by maxwellainatchi** [comment]
@ptsochantaris since the latest update, I started seeing the bug where recently closed issues that are filtered out getting shown in Trailer when they're closed, e.g. 
image

**Comment by kamilpp** [comment]
In my case, comments in merged PRs are still not showing in trailer.

Another issue, the trailer icon often shows a wrong number e.g. right now it shows 6 
image
while there are just 5 items on my trailer list. 
A while back it showed 11 while there were also 5 active PRs on my trailer list. 

I will keep an eye on this and report my findings.

**Comment by maxwellainatchi** [comment]
@ptsochantaris bigger issue that I discovered this morning; review statuses are not updating in trailer anymore. All my approved PRs still say `@x hasn't reviewed yet`. This is a regression from the previous beta build. Is there a way to downgrade without losing data?

**Comment by maxwellainatchi** [comment]
Any update on how to downgrade safely? Or a new build with the fixes? I need the PR statuses/notifications for work

**Comment by ptsochantaris** [comment]
Hi @maxwellainatchi and thanks for reporting the issue, I'll dig into it. If you want to downgrade, since this version does change the DB structure a bit, it may be easiest if you export your settings. install the older version, and if it doesn't migrate your data so ahead and import your previous settings.

**Comment by ptsochantaris** [comment]
Hi @maxwellainatchi I think I found and corrected the issue. Hit "check for updates" and give it a shot. You may need to use the "reload all data" button to refresh your existing review infos.

**Comment by maxwellainatchi** [comment]
It seems like it worked! Will let you know the next time one of my review statuses is updated. Thanks!

**Comment by kamilpp** [comment]
https://github.com/ptsochantaris/trailer/pull/400#issuecomment-608269111

The issue with the wrong number displayed in the bar icon persists. 

The icon shows: 
image

While there are just 2 items on my list (there are couple snoozed items indeed but these previously did not count towards displayed number).

**Comment by ptsochantaris** [comment]
Hi @kamilpp - are the snoozed items visible? If so, is the total number of visible items, including those, correct? Just trying to better understand if there is a bug with counting or whether this is a question of the app’s behaviour. Currently, it is supposed to show the total count of items in a specific menu, but I’m definitely open to adding an option to remove snoozed items from that count, if that’s the issue.

**Comment by ptsochantaris** [comment]
@kamilpp Whoops, sorry, I'm being slow, there's already an option to do that :) So I guess this sounds more like a count bug, but let me know. Also, if you can, let me know if that count is affected when you turn the "include visible snoozed items in menubar count" option on or off. Thanks!

**Comment by kamilpp** [comment]
After I do "Reload all data", there are 7 PRs on my list. For 3 of them, I choose "Snooze until event or manual wake" – then they disappear from the list and the icon shows the correct total (4 items). 

My setting is:
image
but I also tested (the result is the same):
image

So from time to time, after refresh (possibly every time new item appears on the list for the first time), the icon count shows incorrect amount of PRs (I guess it includes snoozed items):
image
(just to be clear – on the screenshot, there are 4 visible items while the bar icon shows 7 items)

Version:

image

**Comment by ptsochantaris** [comment]
@kamilpp Sorry for no movement on that issue recently, I'm finding it hard to reproduce it. From your description it does sound as if something is wrong in the calculation logic related to snoozing while a new item is being added, and I'll be keeping an eye on it. If you are able to get a better sense of when you see this occurring it would definitely help. Also, if you see this occur, and you disable and re-enable "hide snoozed section" does the count correct itself?

**Comment by kamilpp** [comment]
Hi @ptsochantaris 

> Also, if you see this occur, and you disable and re-enable "hide snoozed section" does the count correct itself?

Just tried it – yes, the count corrected itself. Before 10 items (incorrect value, expected 5 items), after toggling there and back this option, 5 items.

**Pull request merged**
